apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
type: Opaque
stringData:
  # Remplacez par vos vraies valeurs ici (ce fichier ne doit pas aller sur GitHub public id√©alement)
  DAGSHUB_USERNAME: "YomnaJL"
  DAGSHUB_TOKEN: "a9a82dbed760d627ec3bced523d52bad2657573a" 
  DAGSHUB_REPO_NAME: "MLOPS_Project"
  MLFLOW_TRACKING_USERNAME: "YomnaJL"
  MLFLOW_TRACKING_PASSWORD: "a9a82dbed760d627ec3bced523d52bad2657573a"